export const GET_TECHSTACK_LIST = 'GET_TECHSTACK_LIST';
export const SET_TECHSTACK_LIST_SUCCESS = 'SET_TECHSTACK_LIST_SUCCESS';
export const GET_PHOTOS_LIST = 'GET_PHOTOS_LIST';
export const SET_PHOTOS_LIST_SUCCESS = 'SET_PHOTOS_LIST_SUCCESS';
